services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: database
    restart: always
    shm_size: 128mb
    hostname: localhost
    env_file:
      -   .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      -   5432
    ports:
      -   5432:5432
  test_db:
    image: postgres:16.3-alpine3.20
    container_name: test_database
    restart: always
    shm_size: 128mb
    hostname: localhost
    env_file:
      - .env
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    expose:
      - 5433
    ports:
      - 5433:5432
  app:
    container_name: myApp
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      -   .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
      TEST_DATABASE_URL: ${DATABASE_URL}
    expose:
      -   3000
    ports:
      -   3000:3000
    volumes:
      -   .:/app
      -   /app/client/node_modules
      -   /app/server/node_modules
    depends_on:
      -   db
      -   test_db